/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

import { environment } from 'src/environments/environment';


const awsmobile = {
    aws_project_region: environment.AWS_REGION,
    aws_cognito_identity_pool_id: environment.AWS_IDENTITY_POOL_ID,
    aws_cognito_region: environment.AWS_REGION,
    aws_user_pools_id: environment.AWS_USER_POOL_ID,
    aws_user_pools_web_client_id: environment.AWS_CLIENT_ID,
    oauth: {
        domain: environment.cognitoUri,
        scope: [
          'email', 'openid', 'aws.cognito.signin.user.admin', 'portal_Vendedor/json.read'
        ],
        redirectSignIn: environment.redirectUri,
        redirectSignOut: environment.redirecSignOutUri,
        responseType: 'code'
    },
    federationTarget: 'COGNITO_USER_AND_IDENTITY_POOLS',
    aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
};


export default awsmobile;
